Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.restaurantaws.reservationservice.handlers.PostHandler
      CodeUri: C:\Users\kordy\IdeaProjects\ReservationService
      Runtime: java17
      Architectures:
        - x86_64